### ISSUE TITLE
Permission issue when trying to enable Security Hub

### ISSUE THREAD

**Issue by BrunoCarrier** [aws-samples/aws-control-tower-securityhub-enabler#17]
I get the following error.  As far as I can tell I am following all steps:

```

[ERROR] ClientError: An error occurred (UnrecognizedClientException) when calling the EnableSecurityHub operation: The security token included in the request is invalid Traceback (most recent call last):  
File "/var/task/securityhub_enabler.py", line 487, in lambda_handler    enable_master(master_session, securityhub_regions, partition)  
File "/var/task/securityhub_enabler.py", line 395, in enable_master    sh_master_client.enable_security_hub()  
File "/var/runtime/botocore/client.py", line 316, in _api_call    return self._make_api_call(operation_name, kwargs)  
File "/var/runtime/botocore/client.py", line 635, in _make_api_call    raise error_class(parsed_response, operation_name) |  
-- | --
```

It might be related to https://github.com/awslabs/aws-securityhub-multiaccount-scripts/issues/23

Here are the regions that are found at https://github.com/aws-samples/aws-control-tower-securityhub-enabler/blob/main/src/securityhub_enabler.py#L412: ‘ap-east-1’, ‘ap-northeast-1’, ‘ap-northeast-2’, ‘ap-south-1’, ‘ap-southeast-1’, ‘ap-southeast-2’, ‘ca-central-1’, ‘eu-central-1’, ‘eu-north-1’, ‘eu-west-1’, ‘eu-west-2’, ‘eu-west-3’, ‘me-south-1’, ‘sa-east-1’, ‘us-east-1’, ‘us-east-2’, ‘us-west-1’, ‘us-west-2’

The organization's master account has access to the ‘me-south-1’ region, yet the audit account doesn't.  See the screenshot below:
![image](https://user-images.githubusercontent.com/10307100/91478849-93af3080-e86e-11ea-98ce-18dad096c716.png)

Enabling all regions (meaning, `me-south-1` was added) on the audit account fixed this issue and allowed for the proper deployment of the Cloudformation template

Some questions arise:
```
1- I'd expect the audit account to be enabled in all regions.  If the audit account doesn't have `me-south-1` but one of the child accounts has it, then we wouldn't have the visibility we want here
2- If the audit account has `me-south-1` enabled but the child account doesn't, would the script fail when trying to run?  A quick analysis indicates that it would
```

I wish I had the cycles to explore these questions, but I currently don't.  Perhaps someone else will

**Comment by silicon-jc** [comment]
TODO: add account enablement checking for each child account before trying to enable
