### ISSUE TITLE
Region for Log Groups is Hard-Coded

### ISSUE THREAD

**Issue by nsack** [aws-samples/aws-control-tower-securityhub-enabler#2]
On the SecurityHubEnablerRole resource for the log permissions the region is hard-coded to "us-east-1". If a user attempts to deploy to another region the Lambda fails to run successfully. This should be set to "{AWS::Region}" to ensure users can deploy to multiple regions based on what their home region is for their master account.

```
-  !Sub 'arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:/aws/lambda/*'
```

**Comment by silicon-jc** [comment]
Thanks @nsack, I'll get this updated immediately.

**Comment by silicon-jc** [comment]
Fix merged in
