### ISSUE TITLE
Cloudformation is stuck at SecurityHubEnablerLambdaFirstRun step and gets roll-backed

### ISSUE THREAD

**Issue by sudheesh-prabhu-ba** [aws-samples/aws-control-tower-securityhub-enabler#22]
Error: Custom Resource failed to stabilize in expected time

Initially I tried with package option as per doc https://aws.amazon.com/blogs/mt/automating-aws-security-hub-alerts-with-aws-control-tower-lifecycle-events/  

Noticed that as per last issue in this git, there is no need to package and we can directly use the zip provided, so I tried that, but still facing the same error

**Comment by silicon-jc** [comment]
Can you look in CloudWatch Logs for the Lambda Logs and see if there are errors there?

**Comment by sudheesh-prabhu-ba** [comment]
Error: Log group does not exist

The specific log group: /aws/lambda/CT-security-hub-SecurityHubEnablerLambda-ZOZT5SNRUIZU does not exist in this account or region

**Comment by chuckcharlie** [comment]
@sudheesh-tcs I had the same issue. Solution is to not use the template file linked on the blog post since it points to the old version. Use the template file in this repo along with the included zip. The blog post needs to be updated to reflect these repo changes.
