### ISSUE TITLE
Python cfn-response module | ClientError: An error occurred (UnrecognizedClientException) when calling the GetEnabledStandards operation: The security token included in the request is invalid

### ISSUE THREAD

**Issue by adnanmansuri44** [aws-samples/aws-control-tower-securityhub-enabler#23]
by selecting region filter to security hub means all aws region. lambda is failed to enable security hub. Also Cloudformation getting failed to create firstrun custom resoruces. 

As mentioned in the readme file cfn-response module to be used. but unable to find the module in the Python file.

CloudFormation Error 

<html>
<body>

2021-09-02 10:19:12 UTC+0400 | FirstRun | CREATE_FAILED | CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [ef4a310d-620c-48fd-843d-21c22df5dbb9]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
-- | -- | -- | --

</body>
</html>

Lambda execution failed error 
<html>
<body>

2021-09-02T09:23:11.189+04:00Copy[ERROR]	2021-09-02T05:23:11.189Z	6ba2106f-ce5a-498a-b819-3d8b8d6e8113	Failed to enable SecurityHub in me-south-1 or 880031744394 | [ERROR] 2021-09-02T05:23:11.189Z 6ba2106f-ce5a-498a-b819-3d8b8d6e8113 Failed to enable SecurityHub in me-south-1 or 880031744394

  | 2021-09-02T09:23:11.508+04:00Copy[ERROR] ClientError: An error occurred (UnrecognizedClientException) when calling the GetEnabledStandards operation: The security token included in the request is invalidTraceback (most recent call last):  File "/var/task/securityhub_enabler.py", line 461, in lambda_handler    enable_master(master_session, securityhub_regions, partition)  File "/var/task/securityhub_enabler.py", line 437, in enable_master    process_security_standards(sh_master_client, partition, region,  File "/var/task/securityhub_enabler.py", line 250, in process_security_standards    enabled_standards = sh_client.get_enabled_standards()  File "/var/runtime/botocore/client.py", line 386, in _api_call    return self._make_api_call(operation_name, kwargs)  File "/var/runtime/botocore/client.py", line 705, in _make_api_call    raise error_class(parsed_response, operation_name) | [ERROR] ClientError: An error occurred (UnrecognizedClientException) when calling the GetEnabledStandards operation: The security token included in the request is invalid Traceback (most recent call last):   File "/var/task/securityhub_enabler.py", line 461, in lambda_handler     enable_master(master_session, securityhub_regions, partition)   File "/var/task/securityhub_enabler.py", line 437, in enable_master     process_security_standards(sh_master_client, partition, region,   File "/var/task/securityhub_enabler.py", line 250, in process_security_standards     enabled_standards = sh_client.get_enabled_standards()   File "/var/runtime/botocore/client.py", line 386, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/runtime/botocore/client.py", line 705, in _make_api_call     raise error_class(parsed_response, operation_name)

</body>
</html>

**Comment by adnanmansuri44** [comment]
Test template and zip available in git. The same error it is getting failed while executing with all supported region security hub. We want to enable a security hub with all standards in **Bahrain** region.

**Comment by silicon-jc** [comment]
Thanks @adnanmansuri44 , it looks like it is because the sts creds aren't valid in the opt-in region.  I'm testing a fix now.

**Comment by silicon-jc** [comment]
If you delete the stack, download the newest template and code, then redeploy it should work.

**Comment by adnanmansuri44** [comment]
Sure let me try new template and code. Thanks. Will update you.

**Comment by adnanmansuri44** [comment]
Solution tested with existing accounts and working as expected. Thanks @cornickj
