### ISSUE TITLE
ControlTower accounts in OU with inherited SCPs are not enabled

### ISSUE THREAD

**Issue by mmiglier** [aws-samples/aws-control-tower-securityhub-enabler#25]
Considering the following org structure:

 - Workloads (OU)
   - Test (OU)
     - AccountA
     - AccountB
   - Prod (OU)
     - AccountC
     - AccountD

When Workloads is enrolled, Test is not attached CT SCP directly, they are inherited.
`list_policies_for_target` only returns policies that are attached directly.
Therefore my accounts are not enabled.

**Comment by silicon-jc** [comment]
@mmiglier I see you have a fix in your fork - did you want to submit a pull request for it?  If so, please see [CONTRIBUTING.md](https://github.com/aws-samples/aws-control-tower-securityhub-enabler/blob/main/CONTRIBUTING.md)

**Comment by mmiglier** [comment]
Hi @cornickj sure I will as soon as I test it.
