### ISSUE TITLE
Getting expected maxLength: 63, actual: 65 #/Code/S3Bucket: failed validation constraint for keyword [pattern] while enabling .

### ISSUE THREAD

**Issue by archit-cd** [aws-samples/aws-control-tower-securityhub-enabler#27]
I am trying to deploy lambda function . I have tried with master branch and latest version  and 2.2 version  but getting same error everytime.
![Screen Shot 2022-08-21 at 12 19 33 PM](https://user-images.githubusercontent.com/87892837/185800962-39035028-a435-49ad-a41f-798ed7e9c98e.png)

**Comment by silicon-jc** [comment]
That error indicates that the S3SourceBucket parameter you are providing is not correct.  You just want the bucket name itself, not the S3 URL, or ARN.

If it is still not working, please share a redacted view of your parameters.

**Comment by archit-cd** [comment]
Thankyou issue resolved :)
