### ISSUE TITLE
securityhub_enabler.py with runtime 3.10 is giving error 

### ISSUE THREAD

**Issue by PRAND2023** [aws-samples/aws-control-tower-securityhub-enabler#31]
Hi Support,

I have updated my control tower security hub Cloud formation template (release in 2019) with  latest version of 2020. Cloud formation template deployment was success but after monitoring Lambda cloud watch logs I see multiple error for   securityhub_enabler.py script at line 612 .Following is attached screenshot for reference. 
![Cloud_watch_log_error](https://github.com/aws-samples/aws-control-tower-securityhub-enabler/assets/153806392/75b390ef-bc97-4de4-8cdd-4bd69331939c)

Till now we not face this issue in previous Python script  .Only reason we updated CF due to deprecated python runtime3.7
Please suggest.

Regards
PRAND

**Comment by silicon-jc** [comment]
Thanks PRAND, I can't seem to duplicate that error. Can you go to the lambda function, configuration tab, and add an environment variable "log_level" and set the value to "INFO", then Test the function? (the test contents don't matter)

**Comment by PRAND2023** [comment]
Hi Cornickj, After changing environment variable "log_level"  value from "ERROR" to "INFO" .I see some activity happening with AWS account .Please have a look. 
![Cloud_watch_log_python3 10](https://github.com/aws-samples/aws-control-tower-securityhub-enabler/assets/153806392/282a16be-70e6-4348-bbbc-d20af8e8684f)

**Comment by silicon-jc** [comment]
Good, those are all normal messages - are the errors still occurring? We might need to wait for the next scheduled trigger to see it, if that is the source of the problem.  There will also be multiple log streams created close together, for the "dispatcher" that is the main trigger the logs will be in the oldest log stream in that group.

**Comment by silicon-jc** [comment]
@PRAND2023 any updates?

**Comment by PRAND2023** [comment]
Hi Cornickj,
There was no lambada log since 14th Dec. I have run test again , There was no error in logs.
I think we are good to close case .Thanks for help.
