### ISSUE TITLE
Automating AWS Security Hub Alerts with AWS Control Tower lifecycle events fails with hanging

### ISSUE THREAD

**Issue by hasinthaindrajee** [aws-samples/aws-control-tower-securityhub-enabler#9]
When this CFT is deployed following the guidlines in [1]. The stack creation fails after long time hanging on the event of Custom::SecurityHubEnablerLambdaFirstRun. It doesn't give any other useful information either. 

Once failed after hanging for a long time I can see that below event is published under stack events. 

FirstRun | CREATE_FAILED | Custom Resource failed to stabilize in expected time

[1] https://aws.amazon.com/blogs/mt/automating-aws-security-hub-alerts-with-aws-control-tower-lifecycle-events/

**Comment by silicon-jc** [comment]
There should be a log group in CloudWatch Logs called /aws/[Stack name]-SecurityHub-Enabler-Lambda-[UID]
If you look at the log streams there, are there any errors?  The custom resource failing means that the Lambda function was called, but never returned a response to CloudFormation so it likely failed to execute.

**Comment by hasinthaindrajee** [comment]
@cornickj : Thanks for the input. However I don't find lot of useful information from the above mentioned log as well. I am quoting them below. However I have removed and modified entries just to make sure nothing internal get exposed. 

2020-05-28T17:07:51.166+05:30
START RequestId: 79945bcc-7f12-45b4-a845- Version: $LATEST

2020-05-28T17:08:01.457+05:30
https://cloudformation-custom-resource-response-mazonaws.com/arn%3/MySecurityHubStack/{}

2020-05-28T17:08:01.457+05:30
Response body:

2020-05-28T17:08:01.457+05:30
{"Status": "SUCCESS", "Reason": "See the details in CloudWatch Log Stream: 2020/05/28/[$LATEST]", "PhysicalResourceId": "2020/05/28/[$LATEST]", "StackId": "", "RequestId": "9c347573-de25-4596-940d-", "LogicalResourceId": "FirstRun", "NoEcho": false, "Data": {}}

2020-05-28T17:08:01.678+05:30
Status code: OK

2020-05-28T17:08:02.235+05:30
END RequestId: 79945bcc-7f12-45b4-a845-

2020-05-28T17:08:02.235+05:30
REPORT RequestId: 79945bcc-7f12-45b4-a845- Duration: 11069.39 ms Billed Duration: 11100 ms Memory Size: 256 MB Max Memory Used: 81 MB Init Duration: 700.97 ms

2020-05-28T17:08:02.235+05:30
RequestId: 79945bcc-7f12-45b4-a845- Error: Runtime exited without providing a reason Runtime.ExitError

2020-05-28T17:08:57.473+05:30
START RequestId: 79945bcc-7f12-45b4-a845- Version: $LATEST

2020-05-28T17:09:08.016+05:30
https://cloudformation-custom-resource-response.s3.amazonaws.com/arn%3Aaws%3Acloudformation%3A%3Astack/MySecurityHubStack/-a0cf-11ea-bed2-%7CFirstRun%-940d-?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-
2020-05-28T17:09:08.016+05:30
Response body:

2020-05-28T17:09:08.016+05:30
{"Status": "SUCCESS", "Reason": "See the details in CloudWatch Log Stream: 2020/05/28/[$LATEST]", "PhysicalResourceId": "2020/05/28/[$LATEST]", "StackId": "", "RequestId": "9c347573-de25-459", "LogicalResourceId": "FirstRun", "NoEcho": false, "Data": {}}

2020-05-28T17:09:08.116+05:30
Status code: OK

2020-05-28T17:09:08.669+05:30
END RequestId: 79945bcc-7f12-45b4-a845-

2020-05-28T17:09:08.669+05:30
REPORT RequestId: 79945bcc-7f12-45b4-a845- Duration: 11192.07 ms Billed Duration: 11200 ms Memory Size: 256 MB Max Memory Used: 36 MB

2020-05-28T17:09:08.669+05:30
RequestId: 79945bcc-7f12-45b4-a845- Error: Runtime exited without providing a reason Runtime.ExitError
Loading newer events

**Comment by silicon-jc** [comment]
I've updated the python to use urllib3 instead of requests.  I don't know if it will help but may provide some more useful logs?

**Comment by hasinthaindrajee** [comment]
Looks like with this change below thing is getting printed while running ./package.sh to build the zip . Is this something expected ?

zip error: Nothing to do! (try: zip --recurse-paths /Users/hasinthaindrajee/work/cloud/tmp/security-hub/aws-control-tower-securityhub-enabler/src/securityhub_enabler.zip . -i .)
	zip warning: securityhub_enabler.zip not found or empty
  adding: securityhub_enabler.py (deflated 76%)

**Comment by silicon-jc** [comment]
That’s ok.  The updated code doesn’t need to package any dependencies, so it is basically just zipping up the .py file.


jason cornick

E:cornickj@amazon.com<mailto:alias@amazon.com?subject=Contact%20Information>| M: +1.936.827.5620<tel:+1.936.827.5620>

On May 28, 2020, at 10:26 PM, Hasintha Indrajee <notifications@github.com> wrote:

﻿

Looks like with this change below thing is getting printed while running ./package.sh to build the zip . Is this something expected ?

zip error: Nothing to do! (try: zip --recurse-paths /Users/hasinthaindrajee/work/cloud/tmp/security-hub/aws-control-tower-securityhub-enabler/src/securityhub_enabler.zip . -i .)
zip warning: securityhub_enabler.zip not found or empty
adding: securityhub_enabler.py (deflated 76%)

**Comment by hasinthaindrajee** [comment]
@cornickj : Looks like with this new change the stack starts up properly. Thanks for the help.
